defaults:
  - _self_
  - aml_config
  - aoai_embedding_config

embedding_config:
  pipeline:
    base_experiment_name: simple_embedding_creation
    tags:
    default_compute_target: isolatedcompute
  mmlu_dataset: clinical_knowledge
  mmlu_split: dev
  source_key: question
  destination_key: question_embedding
  workers: 4
  max_errors: 2
  aoai_embedding_config: ${ default_aoai_embedding_config }